core.validation.error=Error on validating the input parameters {0}

client.pkey.not.exist=Client with ID {0} does not exist

user.already.exists=User with name {0} already exists
user.pkey.already.exists=User with ID {0} already exists
user.pkey.not.exist=User with ID {0} does not exist
user.pk.not.exist=User with PK {0} does not exist
user.name.not.exist=User with name {0} does not exist
user.save.null.argument=User to be saved must not be null
user.password.invalid=Password of User {0} does not match the defined pattern

role.not.exist=Role with name {0} cannot be found. Probably it has been removed
role.pkey.not.exist=Role with ID {0} does not exist

grant.name.already.exists=Grant with name {0} already exists

so.pkey.not.exist=Securityobject with ID {0} does not exist

module.modulename.null.argument=Modulename must not be null
